CREATE TABLE IF NOT EXISTS expenses(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    amount float NOT NULL CHECK (amount > 0),
    concept text,
    dateAdded date NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE IF NOT EXISTS incomes(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    amount float NOT NULL CHECK (amount > 0),
    concept text,
    dateAdded date NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE IF NOT EXISTS users(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    password varchar NOT NULL CHECK (name <> ''),
    email text NOT NULL CHECK (name <> '')
);

CREATE DOMAIN operation_type AS text
CHECK (VALUE= 'Income' OR VALUE= 'Expense');

CREATE TABLE IF NOT EXISTS transactions(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    amount float NOT NULL CHECK (amount > 0),
    concept text,
    transaction_type text,
    date_added date NOT NULL DEFAULT CURRENT_DATE
);